name: checks
on: [push]
jobs:
  build_test:
    runs-on: macos-11
    steps:
      - run: wget https://download.panic.com/playdate_sdk/PlaydateSDK-latest.zip
      - run: unzip PlaydateSDK-latest.zip
      - run: sudo installer -pkg PlaydateSDK-*.pkg -target /
      - run: brew install cmocka
      - uses: actions/checkout@v2
      - run: make
      - run: make test
